name: naz/mulla/photography
favicon: null
layout_spectrum: 0.5603999176528305
typography_spectrum: 0.07862427621148527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5516480263322592
  lightness: 0.014060014393180609
  saturation: 0.5335803981870413
  rhythmicContrast: 0.25900068669579923
purpose: []
