name: naz/mulla/photography
favicon: null
layout_spectrum: 0.74918
typography_spectrum: 0.49883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15110e'
    - '#4d4543'
    - '#b0a6a4'
    - '#7d7371'
    - '#ebe5d9'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
